/*
 * 借词表（**自动生成，勿手改**）：`npm run build:loan`。
 *
 * 数据来源是 sci.lang.japan FAQ 的 "Which Japanese words come from <语言>?"
 * （用户给的测试用例页面：portuguese.html / dutch.html / german.html / russian.html），
 * 也就是**日语里通行的写法**。它和拼读规则是两回事：
 *   规则层 = 照拼写猜（confident:false，配了 key 会交给大模型改）
 *   这张表 = 日语里就是那么写的（confident:true，等同于人工词条）
 * 所以外语行上**先查这张表**，连英语词典都要让路。
 *
 * 原始数据在 tools/vendor/loan/*.txt（带来源 URL 与抓取日期）：de 87, nl 47, pt 33, ru 9。
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.LKLoan = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  /* 键已经折成小写、去掉了空格/连字符/变音符号，查表时用同一套折法 */
  var RAW = {
    de: {
      "adrenalin": "アドレナリン",
      "allergie": "アレルギー",
      "arbeit": "アルバイト",
      "aspirin": "アスピリン",
      "baumkuchen": "バウムクーヘン",
      "bombe": "ボンベ",
      "dachshund": "ダックスフント",
      "damon": "デーモン",
      "demagogie": "デマ",
      "diesel": "ディーゼル",
      "dobermann": "ドーベルマン",
      "energie": "エネルギー",
      "fett": "ヘット",
      "gaze": "ガーゼ",
      "gelande": "ゲレンデ",
      "genom": "ゲノム",
      "gips": "ギプス",
      "gruppe": "グルッペ",
      "gummi": "グミ",
      "haken": "ハーケン",
      "hakenkreuz": "ハーケンクロイツ",
      "harn": "ハルン",
      "hegemonie": "ヘゲモニー",
      "herpes": "ヘルペス",
      "hormon": "ホルモン",
      "hutte": "ヒュッテ",
      "hysterie": "ヒステリー",
      "ideologie": "イデオロギー",
      "impotenz": "インポ",
      "jod": "ヨード",
      "jodel": "ヨーデル",
      "kaffein": "カフェイン",
      "kanon": "カノン",
      "kapsel": "カプセル",
      "karies": "カリエス",
      "karte": "カルテ",
      "kindergarten": "キンダーガルテン",
      "kocher": "コッヘル",
      "kollagen": "コラーゲン",
      "kranke": "クランケ",
      "lied": "リート",
      "lorelei": "ローレライ",
      "lumpen": "ルンペン",
      "magen": "マーゲン",
      "marchen": "メルヘン",
      "masochist": "マゾヒスト",
      "meister": "マイスター",
      "merkmal": "メルクマール",
      "messe": "メッセ",
      "nazi": "ナチ",
      "neurose": "ノイローゼ",
      "nikotin": "ニコチン",
      "oblate": "オブラート",
      "onanie": "オナニー",
      "operation": "オペ",
      "pickel": "ピッケル",
      "poltergeist": "ポルターガイスト",
      "pudel": "プードル",
      "puls": "プルス",
      "rheumatismus": "リューマチ",
      "rontgen": "レントゲン",
      "rucksack": "リュックサック",
      "schale": "シャーレ",
      "schanze": "シャンツェ",
      "schlafsack": "シュラーフ",
      "schnorchel": "シュノーケル",
      "seil": "ザイル",
      "seminar": "ゼミナール",
      "sonde": "ゾンデ",
      "spitz": "スピッツ",
      "sprechchor": "シュプレッヒコール",
      "stock": "ストック",
      "syphilis": "ジフィリス",
      "thema": "テーマ",
      "these": "テーゼ",
      "trachom": "トラホーム",
      "tuberkulin": "ツベルクリン",
      "typhus": "チフス",
      "ultra": "ウルトラー",
      "vakzin": "ワクチン",
      "vaselin": "ワセリン",
      "vektor": "ベクトル",
      "virus": "ビールス",
      "volkswagen": "フォルクスワーゲン",
      "wappen": "ワッペン",
      "windjacke": "ウィンドヤッケ",
      "yoghurt": "ヨーグルト",
    },
    nl: {
      "alcohol": "アルコール",
      "asbest": "アスベスト",
      "bier": "ビール",
      "blik": "ブリキ",
      "boorbank": "ボールバン",
      "dans": "ダンス",
      "doek": "ズック",
      "dok": "ドック",
      "gas": "ガス",
      "glas": "ガラス",
      "gom": "ゴム",
      "hop": "ホップ",
      "hysterie": "ヒステリー",
      "inkt": "インキ",
      "kabas": "カバン",
      "kamfer": "カンフル",
      "kinine": "キニーネ",
      "koffie": "コーヒー",
      "kok": "コック",
      "kompas": "コンパス",
      "kop": "コップ",
      "kraan": "カラン",
      "kurk": "コルク",
      "lamp": "ランプ",
      "lancet": "ランセット",
      "lens": "レンズ",
      "malaria": "マラリヤ",
      "mantel": "マント",
      "marmot": "モルモット",
      "mast": "マスト",
      "mes": "メス",
      "morfine": "モルヒネ",
      "nikkel": "ニッケル",
      "oblaat": "オブラート",
      "ontembaar": "オテンバ",
      "orgel": "オルゴール",
      "pek": "ペンキ",
      "pen": "ペン",
      "pincet": "ピンセット",
      "pistool": "ピストル",
      "pomp": "ポンプ",
      "ransel": "ランドセル",
      "retort": "レトルト",
      "saffraan": "サフラン",
      "schop": "スコップ",
      "siroop": "シロップ",
      "spuit": "スポイト",
    },
    pt: {
      "balanco": "ブランコ",
      "bolo": "ボーロ",
      "botao": "ボタン",
      "capa": "カッパ",
      "capitao": "カピタン",
      "caramelo": "カルメラ",
      "carta": "カルタ",
      "charamela": "チャルメラ",
      "choro": "ショーロ",
      "confeito": "コンペイトー",
      "cristao": "キリシタン",
      "cristo": "キリスト",
      "cruz": "クルス",
      "frasco": "フラスコ",
      "gibao": "ジバン",
      "inglez": "イギリス",
      "jaqueta": "チョッキ",
      "marmelo": "マルメロ",
      "meias": "メリヤス",
      "mirra": "ミイラ",
      "olanda": "オランダ",
      "padre": "バテレン",
      "pao": "パン",
      "raxa": "ラシャ",
      "rosario": "ロザリオ",
      "sabado": "サバト",
      "sabao": "シャボン",
      "saraca": "サラサ",
      "tabaco": "タバコ",
      "totanaga": "トタン",
      "veludo": "ビロード",
      "vidro": "ビードロ",
      "zamboa": "ザボン",
    },
    ru: {
      "борщ": "ボルシチ",
      "блины": "ブリヌイ",
      "икра": "イクラ",
      "комбинат": "コンビナート",
      "матрёшка": "マトリョーシカ",
      "норма": "ノルマ",
      "печка": "ペチカ",
      "пирожки": "ピロシキ",
      "водка": "ヴォトカ",
    },
  };

  var COUNT = 0;
  for (var lang in RAW) {
    if (Object.prototype.hasOwnProperty.call(RAW, lang)) COUNT += Object.keys(RAW[lang]).length;
  }

  return {
    tables: RAW,
    count: COUNT,
    /** 查一张表；没有这张表返回 null（调用方自己决定怎么退化） */
    get: function (lang) {
      return RAW[lang] || null;
    },
  };
});
