/*
 * western-katakana 的种子词表：英文 -> 片假名读音。
 *
 * 这是**唯一**的数据源（`src/core/dict.js` 由 tools/build-dict.js 从它生成，
 * 不要手改生成物）。
 *
 * 数据来自两处：
 *   1. 反转 katakana-terminator 的离线词典（那本来就是"片假名外来语 -> 英文原词"，
 *      反转过来正好是"英文 -> 片假名读音"，而且是真实写法而不是规则拼的）；
 *   2. 手工补的 J-pop 歌词高频词（light / sky / dream 这类规则容易拼错的）。
 *
 * 想加词直接改这里，然后 npm run build:dict。
 */
"use strict";

module.exports = [
  // 单字母词（`a` / `I`）：这两个是英文里真实存在的单词，也是歌词里最常见的一对。
  // 它们不在词频表的候选里（那份表只取长度 >= 2 的词），所以人工放进来。
  { en: "a", kana: "ア" },
  /*
   * `Ave`（拉丁语的"万福"）：**アベ**。
   *
   * 这条改过一次：一开始定的是 アヴェ（Ave Maria = アヴェ・マリア 是通行写法），
   * 但用户指出乐队 `Ave Mujica` 的官方读法就是 **アベ ムジカ** ——
   * 它是歌名/歌手栏里会反复出现的那一个，按用户的口径定死。
   * （阿ヴェ・マリア 写成 アベ・マリア 也通行，所以这一步不亏。）
   */
  { en: "ave", kana: "アベ" },
  { en: "mujica", kana: "ムジカ" },
  /*
   * `Georgette`：ジョージェット（人名/织物）。
   * 用户报的：不在词典时走英文拼写规则，geo / rge 这种拼法规则只能瞎猜，
   * 给出 ゲオーゲターテ。英文的软 g / 硬 g 光看拼写定不下来（get 是硬、gem 是软），
   * 所以专有名词只能人工核 —— 织物义另有 ジョーゼット 的写法。
   */
  { en: "georgette", kana: "ジョージェット" },
  /*
   * `Erika` / `Erik`：**エーリカ / エーリク**（德语人名，长音）。
   *
   * 用户截图：德语歌《Erika》里有一行只有 `Erika` 一个词 —— 整行判不出语种，
   * 罗马音层把它当日语罗马字切成 **エリカ**，而且标成"确定"（蓝色），
   * 大模型那一层永远不会被问到它。德语引擎也兜不住：词首 `er-` 那条规则是给
   * erinnern / Erzählung 这种**非重读前缀**定的（エア…），套到名字上会读成
   * エアイーカ。德语 Erika 是长音 [ˈeːʁika]，日语词典（独和辞典）也写 エーリカ。
   * （英文拼法的 Erica 是 エリカ，不走这两条。）
   */
  { en: "erika", kana: "エーリカ" },
  { en: "erik", kana: "エーリク" },
  /*
   * `Rückkehr`：**リュックケーア**（德语词尾 -r 是元音化的 [ɐ̯]，读 ア 不是 ル）。
   *
   * 为什么人工钉：它不在德语词表（SIGNALS.de.words）里，所以"运行期素材沉淀"那道
   * 流水线会收它 —— 而模型给的是 リュックケール（按拼写读了 r），比引擎的近似还差。
   * 人工词表优先，正好挡住沉淀那条路（promote 脚本看到人工表里有就跳过）。
   */
  { en: "ruckkehr", kana: "リュックケーア" },
  /*
   * 数字与单位（整族钉死）。
   *
   * 怎么发现的：设置面板的预览示例句换成高考听力那句「The shirt is nine pounds
   * fifteen pence.」时，探针发现 `fifteen` 不在词典里，走规则层给的是
   * **フィファテエン**。顺着查了一整族，漏的还不止一个 ——
   * thirteen シアーテエン、fourteen フォアーテエン、sixteen シクステエン、
   * seventeen セベンテエン、eighteen エアイテエン、forty フォータイー、
   * fifty フィファタイー、sixty シクスタイー、seventy セベンタイー、
   * eighty エアイタイー、ninety ニネタイー，而 `nineteen` 更离谱，
   * 先被罗马音层抢走读成 ニネテエン。
   *
   * 原因是这批词**不在那份词频表的前 6000 里**（表里只有 one/three/nine/twenty/
   * thirty 这些），所以从来没进过生成词表。数字读音没有歧义、歌词里又常见
   * （twenty-four、fifty…），与其指望规则层，不如人工钉死。
   */
  { en: "two", kana: "トゥー" },
  { en: "seven", kana: "セブン" },
  { en: "eight", kana: "エイト" },
  { en: "eleven", kana: "イレブン" },
  { en: "thirteen", kana: "サーティーン" },
  { en: "fourteen", kana: "フォーティーン" },
  { en: "fifteen", kana: "フィフティーン" },
  { en: "sixteen", kana: "シックスティーン" },
  { en: "seventeen", kana: "セブンティーン" },
  { en: "eighteen", kana: "エイティーン" },
  { en: "nineteen", kana: "ナインティーン" },
  { en: "forty", kana: "フォーティ" },
  { en: "fifty", kana: "フィフティ" },
  { en: "sixty", kana: "シックスティ" },
  { en: "seventy", kana: "セブンティ" },
  { en: "eighty", kana: "エイティ" },
  { en: "ninety", kana: "ナインティ" },
  { en: "second", kana: "セカンド" },
  { en: "hour", kana: "アワー" },
  { en: "pence", kana: "ペンス" },
  { en: "penny", kana: "ペニー" },
  /*
   * 被罗马音层读歪的常用英文词（审计出来的一批）。
   *
   * 怎么发现的：用户问「the pretender up, … shake, shake, shake it up 里
   * 为什么只有 the 没被矫正」。查下来 the/up/it 是**词典命中**（本来就对，
   * 按设计不问模型），而 `shake` 是**罗马音层**给的 —— `sha-ke` 正好切得干净，
   * 于是读成 **シャケ**（鮭）。层序是「词典 > 罗马音 > 大模型」，
   * 罗马音层一答就没模型什么事了，所以这类词**永远不会被矫正**。
   *
   * 顺手拿 google-10000 英文词频表做了一次审计：9974 个词里 3960 个不在词典，
   * 其中 **240 个**会被罗马音层读成日语罗马字（下面是最常见的一批）。
   * `shake` 在词频表第 8150 位 —— 当初的词典扩展只做了前 6000，它从来没进过候选；
   * `open`(283) / `again`(515) 虽然在 6000 以内，那条生成记录也漏了。
   *
   * **故意不收**的：在日语罗马音里也是真词、两种读法都成立的那些 ——
   * `sake`(サケ)、`dare`(ダレ)、`dame`(ダメ)、`ate`(アテ)、`sage`(サゲ)、
   * `bare`(バレ)、`kai`/`cho`/`sen` 这类。钉死反而会毁掉罗马音歌词，
   * 交给大模型按语境判更合适（把「大模型」拖到「罗马音」上面就是让模型仲裁）。
   */
  { en: "open", kana: "オープン" },
  { en: "again", kana: "アゲイン" },
  { en: "tongue", kana: "タン" },
  { en: "gauge", kana: "ゲージ" },
  { en: "gage", kana: "ゲージ" },
  { en: "engage", kana: "エンゲージ" },
  { en: "noon", kana: "ヌーン" },
  { en: "dozen", kana: "ダズン" },
  { en: "mate", kana: "メイト" },
  { en: "pie", kana: "パイ" },
  { en: "chose", kana: "チョーズ" },
  { en: "ripe", kana: "ライプ" },
  { en: "joke", kana: "ジョーク" },
  { en: "bean", kana: "ビーン" },
  { en: "bee", kana: "ビー" },
  { en: "retain", kana: "リテイン" },
  { en: "begun", kana: "ビガン" },
  { en: "parade", kana: "パレード" },
  { en: "pope", kana: "ポープ" },
  { en: "rebate", kana: "リベート" },
  { en: "immune", kana: "イミューン" },
  { en: "arise", kana: "アライズ" },
  { en: "intense", kana: "インテンス" },
  { en: "intake", kana: "インテイク" },
  { en: "assure", kana: "アシュア" },
  { en: "refuse", kana: "リフューズ" },
  { en: "nuke", kana: "ニューク" },
  { en: "arrange", kana: "アレンジ" },
  { en: "horizon", kana: "ホライズン" },
  { en: "minimize", kana: "ミニマイズ" },
  { en: "gotten", kana: "ガトゥン" },
  { en: "shade", kana: "シェイド" },
  { en: "sudden", kana: "サドゥン" },
  { en: "rope", kana: "ロープ" },
  { en: "hose", kana: "ホース" },
  { en: "tattoo", kana: "タトゥー" },
  { en: "shake", kana: "シェイク" },
  { en: "sunrise", kana: "サンライズ" },
  { en: "shame", kana: "シェイム" },
  { en: "metadata", kana: "メタデータ" },
  { en: "basename", kana: "ベースネーム" },
  { en: "roommate", kana: "ルームメイト" },
  { en: "reggae", kana: "レゲエ" },
  { en: "gore", kana: "ゴア" },
  { en: "gazette", kana: "ガゼット" },
  { en: "rage", kana: "レイジ" },
  { en: "undo", kana: "アンドゥ" },
  { en: "bite", kana: "バイト" },
  { en: "ozone", kana: "オゾン" },
  { en: "penguin", kana: "ペンギン" },
  { en: "terrain", kana: "テレイン" },
  { en: "mime", kana: "マイム" },
  { en: "keen", kana: "キーン" },
  { en: "dosage", kana: "ドーセージ" },
  { en: "token", kana: "トークン" },
  { en: "kinda", kana: "カインダ" },
  { en: "gotta", kana: "ガタ" },
  { en: "duo", kana: "デュオ" },
  { en: "dome", kana: "ドーム" },
  { en: "ware", kana: "ウェア" },
  { en: "jade", kana: "ジェイド" },
  { en: "pose", kana: "ポーズ" },
  { en: "dense", kana: "デンス" },
  { en: "mandate", kana: "マンデート" },
  { en: "maiden", kana: "メイデン" },
  { en: "pike", kana: "パイク" },
  { en: "poison", kana: "ポイズン" },
  { en: "potato", kana: "ポテト" },
  { en: "marijuana", kana: "マリファナ" },
  { en: "mediterranean", kana: "メディタレニアン" },
  { en: "pete", kana: "ピート" },
  { en: "aurora", kana: "オーロラ" },
  { en: "jake", kana: "ジェイク" },
  { en: "jamie", kana: "ジェイミー" },
  { en: "joan", kana: "ジョーン" },
  { en: "annie", kana: "アニー" },
  { en: "robbie", kana: "ロビー" },
  { en: "shannon", kana: "シャノン" },
  { en: "morrison", kana: "モリソン" },
  { en: "monroe", kana: "モンロー" },
  { en: "diane", kana: "ダイアン" },
  { en: "diana", kana: "ダイアナ" },
  { en: "eugene", kana: "ユージン" },
  { en: "reunion", kana: "リユニオン" },
  { en: "sudan", kana: "スーダン" },
  { en: "guyana", kana: "ガイアナ" },
  { en: "andorra", kana: "アンドラ" },
  { en: "dubai", kana: "ドバイ" },
  { en: "yukon", kana: "ユーコン" },
  { en: "tahoe", kana: "タホー" },
  { en: "oman", kana: "オマーン" },
  { en: "niagara", kana: "ナイアガラ" },
  /*
   * 感叹词 / 拟声词，以及"罗马音层会读歪、但确实不是日语词"的那些英文词。
   *
   * 用户报的两件事：
   *   1. `Yeah` 读成了 イェア —— 日语里唱的是**イェイ**，人工钉死；
   *   2. `Shoo` / `Gimme` 被读成 ショオ / ギッメ —— 这两个词**词典里根本没有**，
   *      于是被罗马音层（它是"能切成音节就收"）抢走了。同类还有下面这些
   *      （Harrison ハッリソン、Mason マソン、midi ミヂ…），一起补上。
   * 短音节（`do`/`re`/`mi`/`me`/`mo`…）**故意不收**：它们两种读法都成立
   * （英文 ドゥー/リー/ミー vs 唱名·罗马字 ド/レ/ミ），钉死反而会错，
   * 交给大模型按整句语境判（这些词会被标成"没把握"，见 main.js）。
   */
  { en: "yeah", kana: "イェイ" },
  { en: "yea", kana: "イェイ" },
  { en: "yay", kana: "イェイ" },
  { en: "shoo", kana: "シュー" },
  { en: "gimme", kana: "ギミー" },
  { en: "woo", kana: "ウー" },
  { en: "whoo", kana: "ウー" },
  { en: "harrison", kana: "ハリソン" },
  { en: "penn", kana: "ペン" },
  { en: "midi", kana: "ミディ" },
  { en: "unto", kana: "アントゥ" },
  { en: "mason", kana: "メイソン" },
  { en: "rouge", kana: "ルージュ" },
  { en: "genome", kana: "ゲノム" },
  { en: "indie", kana: "インディー" },
  { en: "audi", kana: "アウディ" },
  { en: "eddie", kana: "エディ" },
  { en: "hindu", kana: "ヒンドゥー" },
  { en: "dude", kana: "デュード" },
  { en: "emma", kana: "エマ" },
  { en: "fujitsu", kana: "フジツウ" },
  { en: "marina", kana: "マリーナ" },
  { en: "muze", kana: "ミューズ" },
  { en: "kinase", kana: "キナーゼ" },
  /*
   * 常见缩写（用户报的 `Mr.` / `Dr.`）：日语里念的是**整个词**，不是字母名。
   * 它们会先于规则层命中，所以放在这里就是权威写法。
   * 有歧义的没收：`St.`（セント / ストリート）、`No.`（ナンバー / ノー）。
   */
  { en: "mr", kana: "ミスター" },
  { en: "mrs", kana: "ミセス" },
  { en: "ms", kana: "ミズ" },
  { en: "dr", kana: "ドクター" },
  { en: "prof", kana: "プロフェッサー" },
  { en: "jr", kana: "ジュニア" },
  { en: "sr", kana: "シニア" },
  { en: "vs", kana: "バーサス" },
  { en: "etc", kana: "エトセトラ" },
  { en: "ltd", kana: "リミテッド" },
  { en: "inc", kana: "インク" },
  { en: "access", kana: "アクセス" },
  { en: "accessories", kana: "アクセサリー" },
  { en: "account", kana: "アカウント" },
  { en: "action", kana: "アクション" },
  { en: "alcohol", kana: "アルコール" },
  { en: "algorithm", kana: "アルゴリズム" },
  { en: "analog", kana: "アナログ" },
  { en: "android", kana: "アンドロイド" },
  { en: "anime", kana: "アニメ" },
  { en: "answer", kana: "アンサー" },
  { en: "app", kana: "アプリ" },
  { en: "apple", kana: "アップル" },
  { en: "application", kana: "アプリケーション" },
  { en: "baby", kana: "ベイビー" },
  { en: "bag", kana: "カバン" },
  { en: "balance", kana: "バランス" },
  { en: "ball", kana: "ボール" },
  { en: "barbecue", kana: "バーベキュー" },
  { en: "bargain", kana: "バーゲン" },
  { en: "basketball", kana: "バスケットボール" },
  { en: "battery", kana: "バッテリー" },
  { en: "beat", kana: "ビート" },
  { en: "bed", kana: "ベッド" },
  { en: "beer", kana: "ビール" },
  { en: "belt", kana: "ベルト" },
  { en: "bike", kana: "バイク" },
  { en: "biscuit", kana: "ビスケット" },
  { en: "blog", kana: "ブログ" },
  { en: "blue", kana: "ブルー" },
  { en: "boom", kana: "ブーム" },
  { en: "brand", kana: "ブランド" },
  { en: "bread", kana: "パン" },
  { en: "brochure", kana: "パンフレット" },
  { en: "browser", kana: "ブラウザ" },
  { en: "bug", kana: "バグ" },
  { en: "bus", kana: "バス" },
  { en: "business", kana: "ビジネス" },
  { en: "butter", kana: "バター" },
  { en: "button", kana: "ボタン" },
  { en: "cable", kana: "ケーブル" },
  { en: "cafe", kana: "カフェ" },
  { en: "cake", kana: "ケーキ" },
  { en: "calendar", kana: "カレンダー" },
  { en: "call", kana: "コール" },
  { en: "camera", kana: "カメラ" },
  { en: "cameraman", kana: "カメラマン" },
  { en: "campaign", kana: "キャンペーン" },
  { en: "camping", kana: "キャンプ" },
  { en: "card", kana: "カード" },
  { en: "carnival", kana: "カーニバル" },
  { en: "case", kana: "ケース" },
  { en: "catalog", kana: "カタログ" },
  { en: "chair", kana: "イス" },
  { en: "chance", kana: "チャンス" },
  { en: "character", kana: "キャラクター" },
  { en: "chat", kana: "チャット" },
  { en: "check", kana: "チェック" },
  { en: "cheese", kana: "チーズ" },
  { en: "chip", kana: "チップ" },
  { en: "chocolate", kana: "チョコレート" },
  { en: "cigarette", kana: "タバコ" },
  { en: "cinema", kana: "シネマ" },
  { en: "city", kana: "シティ" },
  { en: "classic", kana: "クラシック" },
  { en: "click", kana: "クリック" },
  { en: "client", kana: "クライアント" },
  { en: "cloud", kana: "クラウド" },
  { en: "clover", kana: "クローバー" },
  { en: "coach", kana: "コーチ" },
  { en: "coat", kana: "コート" },
  { en: "cocktail", kana: "カクテル" },
  { en: "code", kana: "コード" },
  { en: "coding", kana: "コーディング" },
  { en: "coffee", kana: "コーヒー" },
  { en: "cola", kana: "コーラ" },
  { en: "comedy", kana: "コメディ" },
  { en: "comment", kana: "コメント" },
  { en: "compilation", kana: "コンパイル" },
  { en: "complaint", kana: "クレーム" },
  { en: "computer", kana: "コンピューター" },
  { en: "concert", kana: "コンサート" },
  { en: "connector", kana: "コネクタ" },
  { en: "content", kana: "コンテンツ" },
  { en: "control", kana: "コントロール" },
  { en: "copy", kana: "コピー" },
  { en: "cost", kana: "コスト" },
  { en: "country", kana: "カントリー" },
  { en: "culture", kana: "カルチャー" },
  { en: "curry", kana: "カレー" },
  { en: "curtain", kana: "カーテン" },
  { en: "cut", kana: "カット" },
  { en: "cycling", kana: "サイクリング" },
  { en: "dance", kana: "ダンス" },
  { en: "data", kana: "データ" },
  { en: "database", kana: "データベース" },
  { en: "day", kana: "デイ" },
  { en: "debug", kana: "デバッグ" },
  { en: "design", kana: "デザイン" },
  { en: "designer", kana: "デザイナー" },
  { en: "destiny", kana: "デスティニー" },
  { en: "device", kana: "デバイス" },
  { en: "digital", kana: "デジタル" },
  { en: "diorama", kana: "ジオラマ" },
  { en: "directory", kana: "ディレクトリ" },
  { en: "disk", kana: "ディスク" },
  { en: "display", kana: "ディスプレイ" },
  { en: "document", kana: "ドキュメント" },
  { en: "download", kana: "ダウンロード" },
  { en: "drama", kana: "ドラマ" },
  { en: "dream", kana: "ドリーム" },
  { en: "dress", kana: "ドレス" },
  { en: "drive", kana: "ドライブ" },
  { en: "driver", kana: "ドライバ" },
  { en: "drum", kana: "ドラム" },
  { en: "duet", kana: "デュエット" },
  { en: "email", kana: "メール" },
  { en: "encore", kana: "アンコール" },
  { en: "energy", kana: "エナジー" },
  { en: "engine", kana: "エンジン" },
  { en: "engineer", kana: "エンジニア" },
  { en: "error", kana: "エラー" },
  { en: "event", kana: "イベント" },
  { en: "facebook", kana: "フェイスブック" },
  { en: "fall", kana: "フォール" },
  { en: "fantasy", kana: "ファンタジー" },
  { en: "fax", kana: "ファックス" },
  { en: "festival", kana: "フェスティバル" },
  { en: "fever", kana: "フィーバー" },
  { en: "file", kana: "ファイル" },
  { en: "flow", kana: "フロウ" },
  { en: "flower", kana: "フラワー" },
  { en: "folder", kana: "フォルダ" },
  { en: "forever", kana: "フォーエバー" },
  { en: "framework", kana: "フレームワーク" },
  { en: "future", kana: "フューチャー" },
  { en: "games", kana: "ゲーム" },
  { en: "garden", kana: "ガーデン" },
  { en: "gas", kana: "ガス" },
  { en: "gasoline", kana: "ガソリン" },
  { en: "gift", kana: "ギフト" },
  { en: "girl", kana: "ガール" },
  { en: "glory", kana: "グローリー" },
  { en: "goal", kana: "ゴール" },
  { en: "golf", kana: "ゴルフ" },
  { en: "google", kana: "グーグル" },
  { en: "group", kana: "グループ" },
  { en: "guitar", kana: "ギター" },
  { en: "gym", kana: "ジム" },
  { en: "hacking", kana: "ハッキング" },
  { en: "hamburger", kana: "ハンバーガー" },
  { en: "handbag", kana: "ハンドバッグ" },
  { en: "handle", kana: "ハンドル" },
  { en: "happy", kana: "ハッピー" },
  { en: "hardware", kana: "ハードウェア" },
  { en: "harmony", kana: "ハーモニー" },
  { en: "heart", kana: "ハート" },
  { en: "hero", kana: "ヒーロー" },
  { en: "heroine", kana: "ヒロイン" },
  { en: "high", kana: "ハイ" },
  { en: "history", kana: "ヒストリー" },
  { en: "horror", kana: "ホラー" },
  { en: "hotel", kana: "ホテル" },
  { en: "i", kana: "アイ" }, // 英文的 "I"：アイ（罗马音里的裸 i = イ，见 letters.js 里的取舍说明）
  { en: "icon", kana: "アイコン" },
  { en: "idea", kana: "アイデア" },
  { en: "image", kana: "イメージ" },
  { en: "installation", kana: "インストール" },
  { en: "interface", kana: "インターフェース" },
  { en: "internet", kana: "インターネット" },
  { en: "interview", kana: "インタビュー" },
  { en: "jam", kana: "ジャム" },
  { en: "jazz", kana: "ジャズ" },
  { en: "juice", kana: "ジュース" },
  { en: "karaoke", kana: "カラオケ" },
  { en: "keyboard", kana: "キーボード" },
  { en: "kiss", kana: "キス" },
  { en: "kitchen", kana: "キッチン" },
  { en: "know", kana: "ノウ" },
  { en: "label", kana: "ラベル" },
  { en: "laser", kana: "レーザー" },
  { en: "leader", kana: "リーダー" },
  { en: "letter", kana: "レター" },
  { en: "level", kana: "レベル" },
  { en: "library", kana: "ライブラリ" },
  { en: "life", kana: "ライフ" },
  { en: "light", kana: "ライト" },
  { en: "live", kana: "ライブ" },
  { en: "lock", kana: "ロック" },
  { en: "log", kana: "ログ" },
  { en: "lonely", kana: "ロンリー" },
  { en: "love", kana: "ラブ" },
  { en: "manga", kana: "マンガ" },
  { en: "manners", kana: "マナー" },
  { en: "marathon", kana: "マラソン" },
  { en: "market", kana: "マーケット" },
  { en: "marketing", kana: "マーケティング" },
  { en: "media", kana: "メディア" },
  { en: "meeting", kana: "ミーティング" },
  { en: "melody", kana: "メロディー" },
  { en: "member", kana: "メンバー" },
  { en: "memory", kana: "メモリー" },
  { en: "menu", kana: "メニュー" },
  { en: "message", kana: "メッセージ" },
  { en: "microphone", kana: "マイク" },
  { en: "microsoft", kana: "マイクロソフト" },
  { en: "milk", kana: "ミルク" },
  { en: "mind", kana: "マインド" },
  { en: "miracle", kana: "ミラクル" },
  { en: "module", kana: "モジュール" },
  { en: "monitor", kana: "モニター" },
  { en: "moon", kana: "ムーン" },
  { en: "moonlight", kana: "ムーンライト" },
  { en: "motivation", kana: "モチベーション" },
  { en: "mouse", kana: "マウス" },
  { en: "multimedia", kana: "マルチメディア" },
  { en: "music", kana: "ミュージック" },
  { en: "mystery", kana: "ミステリー" },
  { en: "nature", kana: "ネイチャー" },
  { en: "network", kana: "ネットワーク" },
  { en: "never", kana: "ネバー" },
  { en: "news", kana: "ニュース" },
  { en: "night", kana: "ナイト" },
  { en: "notes", kana: "ノーツ" },
  { en: "office", kana: "オフィス" },
  { en: "offline", kana: "オフライン" },
  { en: "online", kana: "オンライン" },
  { en: "only", kana: "オンリー" },
  { en: "opera", kana: "オペラ" },
  { en: "orchestra", kana: "オーケストラ" },
  { en: "over", kana: "オーバー" },
  { en: "pants", kana: "ズボン" },
  { en: "partner", kana: "パートナー" },
  { en: "party", kana: "パーティー" },
  { en: "passport", kana: "パスポート" },
  { en: "password", kana: "パスワード" },
  { en: "pasta", kana: "パスタ" },
  { en: "pattern", kana: "パターン" },
  { en: "pen", kana: "ペン" },
  { en: "piano", kana: "ピアノ" },
  { en: "picnic", kana: "ピクニック" },
  { en: "picture", kana: "ピクチャー" },
  { en: "pizza", kana: "ピザ" },
  { en: "plan", kana: "プラン" },
  { en: "pleasure", kana: "プレジャー" },
  { en: "plugin", kana: "プラグイン" },
  { en: "pocket", kana: "ポケット" },
  { en: "points", kana: "ポイント" },
  { en: "pool", kana: "プール" },
  { en: "pops", kana: "ポップス" },
  { en: "poster", kana: "ポスター" },
  { en: "power", kana: "パワー" },
  { en: "present", kana: "プレゼント" },
  { en: "presentation", kana: "プレゼン" },
  { en: "printer", kana: "プリンター" },
  { en: "program", kana: "プログラム" },
  { en: "programmer", kana: "プログラマー" },
  { en: "programming", kana: "プログラミング" },
  { en: "project", kana: "プロジェクト" },
  { en: "radar", kana: "レーダー" },
  { en: "radio", kana: "ラジオ" },
  { en: "rain", kana: "レイン" },
  { en: "rainbow", kana: "レインボー" },
  { en: "ranking", kana: "ランキング" },
  { en: "reason", kana: "リーズン" },
  { en: "report", kana: "レポート" },
  { en: "restaurant", kana: "レストラン" },
  { en: "rhythm", kana: "リズム" },
  { en: "ribbon", kana: "リボン" },
  { en: "right", kana: "ライト" },
  { en: "risk", kana: "リスク" },
  { en: "river", kana: "リバー" },
  { en: "road", kana: "ロード" },
  { en: "robot", kana: "ロボット" },
  { en: "romance", kana: "ロマンス" },
  { en: "rules", kana: "ルール" },
  { en: "salad", kana: "サラダ" },
  { en: "sale", kana: "セール" },
  { en: "sample", kana: "サンプル" },
  { en: "sandals", kana: "サンダル" },
  { en: "sandwich", kana: "サンドイッチ" },
  { en: "scanner", kana: "スキャナー" },
  { en: "scene", kana: "シーン" },
  { en: "schedule", kana: "スケジュール" },
  { en: "score", kana: "スコア" },
  { en: "screen", kana: "スクリーン" },
  { en: "screwdriver", kana: "ドライバー" },
  { en: "sea", kana: "シー" },
  { en: "season", kana: "シーズン" },
  { en: "security", kana: "セキュリティ" },
  { en: "sense", kana: "センス" },
  { en: "sensor", kana: "センサー" },
  { en: "server", kana: "サーバ" },
  { en: "service", kana: "サービス" },
  { en: "shine", kana: "シャイン" },
  { en: "shirt", kana: "シャツ" },
  { en: "shop", kana: "ショップ" },
  { en: "shopping", kana: "ショッピング" },
  { en: "shower", kana: "シャワー" },
  { en: "sign", kana: "サイン" },
  { en: "simulation", kana: "シミュレーション" },
  { en: "site", kana: "サイト" },
  { en: "size", kana: "サイズ" },
  { en: "skating", kana: "スケート" },
  { en: "skiing", kana: "スキー" },
  { en: "skirt", kana: "スカート" },
  { en: "sky", kana: "スカイ" },
  { en: "smartphone", kana: "スマホ" },
  { en: "smile", kana: "スマイル" },
  { en: "snow", kana: "スノウ" },
  { en: "soccer", kana: "サッカー" },
  { en: "sofa", kana: "ソファ" },
  { en: "software", kana: "ソフトウェア" },
  { en: "solo", kana: "ソロ" },
  { en: "song", kana: "ソング" },
  { en: "soul", kana: "ソウル" },
  { en: "sound", kana: "サウンド" },
  { en: "soup", kana: "スープ" },
  { en: "source", kana: "ソース" },
  { en: "spaghetti", kana: "スパゲッティ" },
  { en: "speaker", kana: "スピーカー" },
  { en: "speech", kana: "スピーチ" },
  { en: "speed", kana: "スピード" },
  { en: "spirit", kana: "スピリット" },
  { en: "sports", kana: "スポーツ" },
  { en: "staff", kana: "スタッフ" },
  { en: "stage", kana: "ステージ" },
  { en: "stamina", kana: "スタミナ" },
  { en: "star", kana: "スター" },
  { en: "starlight", kana: "スターライト" },
  { en: "storage", kana: "ストレージ" },
  { en: "story", kana: "ストーリー" },
  { en: "streaming", kana: "ストリーミング" },
  { en: "stress", kana: "ストレス" },
  { en: "studio", kana: "スタジオ" },
  { en: "style", kana: "スタイル" },
  { en: "summer", kana: "サマー" },
  { en: "sun", kana: "サン" },
  { en: "sunglasses", kana: "サングラス" },
  { en: "sunshine", kana: "サンシャイン" },
  { en: "super", kana: "スーパー" },
  { en: "supermarket", kana: "スーパーマーケット" },
  { en: "sweater", kana: "セーター" },
  { en: "switch", kana: "スイッチ" },
  { en: "symphony", kana: "シンフォニー" },
  { en: "system", kana: "システム" },
  { en: "table", kana: "テーブル" },
  { en: "tablet", kana: "タブレット" },
  { en: "taxi", kana: "タクシー" },
  { en: "team", kana: "チーム" },
  { en: "teamwork", kana: "チームワーク" },
  { en: "television", kana: "テレビ" },
  { en: "tempo", kana: "テンポ" },
  { en: "tennis", kana: "テニス" },
  { en: "test", kana: "テスト" },
  { en: "theme", kana: "テーマ" },
  { en: "ticket", kana: "チケット" },
  { en: "time", kana: "タイム" },
  { en: "timing", kana: "タイミング" },
  { en: "tires", kana: "タイヤ" },
  { en: "title", kana: "タイトル" },
  { en: "today", kana: "トゥデイ" },
  { en: "together", kana: "トゥゲザー" },
  { en: "toilet", kana: "トイレ" },
  { en: "tomorrow", kana: "トゥモロー" },
  { en: "topic", kana: "トピック" },
  { en: "touch", kana: "タッチ" },
  { en: "tour", kana: "ツアー" },
  { en: "training", kana: "トレーニング" },
  { en: "travel", kana: "トラベル" },
  { en: "treasure", kana: "トレジャー" },
  { en: "trend", kana: "トレンド" },
  { en: "trouble", kana: "トラブル" },
  { en: "truck", kana: "トラック" },
  { en: "twitter", kana: "ツイッター" },
  { en: "type", kana: "タイプ" },
  { en: "update", kana: "アップデート" },
  { en: "upgrade", kana: "アップグレード" },
  { en: "upload", kana: "アップロード" },
  { en: "version", kana: "バージョン" },
  { en: "victory", kana: "ヴィクトリー" },
  { en: "video", kana: "ビデオ" },
  { en: "violin", kana: "バイオリン" },
  { en: "virus", kana: "ウイルス" },
  { en: "voice", kana: "ボイス" },
  { en: "volleyball", kana: "バレーボール" },
  { en: "volunteer", kana: "ボランティア" },
  { en: "wall", kana: "ウォール" },
  { en: "wave", kana: "ウェイブ" },
  { en: "way", kana: "ウェイ" },
  { en: "whiskey", kana: "ウイスキー" },
  { en: "why", kana: "ホワイ" },
  { en: "wind", kana: "ウィンド" },
  { en: "window", kana: "ウィンドウ" },
  { en: "windows", kana: "ウィンドウズ" },
  { en: "wine", kana: "ワイン" },
  { en: "winter", kana: "ウィンター" },
  { en: "world", kana: "ワールド" },
  { en: "yesterday", kana: "イエスタデイ" },
  { en: "yoga", kana: "ヨガ" },
  { en: "youtube", kana: "ユーチューブ" },

  /* 第二批：最常见的变形词与歌词高频词（规则读不准，直接进词典） */
  { en: "amazing", kana: "アメイジング" },
  { en: "angels", kana: "エンジェルズ" },
  { en: "another", kana: "アナザー" },
  { en: "autumn", kana: "オータム" },
  { en: "baby", kana: "ベイビー" },
  { en: "beginning", kana: "ビギニング" },
  { en: "believer", kana: "ビリーバー" },
  { en: "believing", kana: "ビリービング" },
  { en: "brightness", kana: "ブライトネス" },
  { en: "burning", kana: "バーニング" },
  { en: "calling", kana: "コーリング" },
  { en: "candy", kana: "キャンディ" },
  { en: "cherry", kana: "チェリー" },
  { en: "chocolate", kana: "チョコレート" },
  { en: "clouds", kana: "クラウズ" },
  { en: "colors", kana: "カラーズ" },
  { en: "crying", kana: "クライング" },
  { en: "dancer", kana: "ダンサー" },
  { en: "dancing", kana: "ダンシング" },
  { en: "darkness", kana: "ダークネス" },
  { en: "days", kana: "デイズ" },
  { en: "distance", kana: "ディスタンス" },
  { en: "dreamer", kana: "ドリーマー" },
  { en: "dreaming", kana: "ドリーミング" },
  { en: "dreams", kana: "ドリームズ" },
  { en: "endless", kana: "エンドレス" },
  { en: "everyone", kana: "エブリワン" },
  { en: "everything", kana: "エブリシング" },
  { en: "exciting", kana: "エキサイティング" },
  { en: "eyes", kana: "アイズ" },
  { en: "falling", kana: "フォーリング" },
  { en: "feeling", kana: "フィーリング" },
  { en: "finally", kana: "ファイナリー" },
  { en: "flowers", kana: "フラワーズ" },
  { en: "flying", kana: "フライング" },
  { en: "forever", kana: "フォーエバー" },
  { en: "friends", kana: "フレンズ" },
  { en: "future", kana: "フューチャー" },
  { en: "glowing", kana: "グロウイング" },
  { en: "goodbye", kana: "グッバイ" },
  { en: "growing", kana: "グロウイング" },
  { en: "hands", kana: "ハンズ" },
  { en: "happiness", kana: "ハピネス" },
  { en: "healing", kana: "ヒーリング" },
  { en: "hearts", kana: "ハーツ" },
  { en: "hello", kana: "ハロー" },
  { en: "hey", kana: "ヘイ" },
  { en: "holding", kana: "ホールディング" },
  { en: "honey", kana: "ハニー" },
  { en: "kisses", kana: "キッシズ" },
  { en: "lights", kana: "ライツ" },
  { en: "living", kana: "リビング" },
  { en: "loneliness", kana: "ロンリネス" },
  { en: "lover", kana: "ラバー" },
  { en: "loving", kana: "ラビング" },
  { en: "maybe", kana: "メイビー" },
  { en: "meaning", kana: "ミーニング" },
  { en: "memories", kana: "メモリーズ" },
  { en: "missing", kana: "ミッシング" },
  { en: "moment", kana: "モーメント" },
  { en: "moving", kana: "ムービング" },
  { en: "nothing", kana: "ナッシング" },
  { en: "ok", kana: "オーケー" },
  { en: "passing", kana: "パッシング" },
  { en: "player", kana: "プレイヤー" },
  { en: "really", kana: "リアリー" },
  { en: "running", kana: "ランニング" },
  { en: "sadness", kana: "サドネス" },
  { en: "seasons", kana: "シーズンズ" },
  { en: "shadows", kana: "シャドウズ" },
  { en: "shining", kana: "シャイニング" },
  { en: "silence", kana: "サイレンス" },
  { en: "singer", kana: "シンガー" },
  { en: "singing", kana: "シンギング" },
  { en: "slowly", kana: "スローリー" },
  { en: "smiling", kana: "スマイリング" },
  { en: "somebody", kana: "サムバディ" },
  { en: "someone", kana: "サムワン" },
  { en: "something", kana: "サムシング" },
  { en: "spring", kana: "スプリング" },
  { en: "stars", kana: "スターズ" },
  { en: "stories", kana: "ストーリーズ" },
  { en: "strawberry", kana: "ストロベリー" },
  { en: "sugar", kana: "シュガー" },
  { en: "summer", kana: "サマー" },
  { en: "surely", kana: "シュアリー" },
  { en: "tears", kana: "ティアーズ" },
  { en: "together", kana: "トゥゲザー" },
  { en: "tomorrow", kana: "トゥモロー" },
  { en: "tonight", kana: "トゥナイト" },
  { en: "trying", kana: "トライイング" },
  { en: "voices", kana: "ボイシズ" },
  { en: "waves", kana: "ウェイブズ" },
  { en: "whatever", kana: "ワットエバー" },
  { en: "whenever", kana: "ホエネバー" },
  { en: "wherever", kana: "ホエアエバー" },
  { en: "winter", kana: "ウィンター" },
  { en: "wishes", kana: "ウィッシズ" },
  { en: "wow", kana: "ワウ" },
  { en: "yesterday", kana: "イエスタデイ" },
  /*
   * 不发音字母的常用英文词 —— 用户问的正是这一类：
   * "没有歧音的词语能否直接写入词典"。能，而且**就该**这么办。
   *
   * 背景：规则层是"照拼写猜"，哑音猜不出来（`Knock`→ナオック、`wrist`→ライサト、
   * 词尾 `-mb` 的 b 也照读）。规则层的两条通例已经补上了（词首 kn/wr/gn/ps/pn、
   * 词尾 -mb，见 reading.js 的 EN_SILENT_HEAD），但下面这些词要么有例外
   * （number ナンバー vs plumber プラマー）、要么连着其它不规则拼写
   * （subtle サトル、island アイランド、people ピープル），人工钉死最省事。
   *
   * 判据只有一条：**读法唯一**（日语里就这么写，没有第二种）。两可的照旧不收。
   */
  { en: "knock", kana: "ノック" },
  { en: "knocking", kana: "ノッキング" },
  { en: "knocked", kana: "ノックド" },
  { en: "knee", kana: "ニー" },
  { en: "kneel", kana: "ニール" },
  { en: "knit", kana: "ニット" },
  { en: "knob", kana: "ノブ" },
  { en: "knot", kana: "ノット" },
  { en: "wrist", kana: "リスト" },
  { en: "wreck", kana: "レック" },
  { en: "wrapped", kana: "ラップト" },
  { en: "wrapping", kana: "ラッピング" },
  { en: "psalm", kana: "サーム" },
  { en: "pneumonia", kana: "ニューモニア" },
  { en: "comb", kana: "コーム" },
  { en: "climb", kana: "クライム" },
  { en: "climbing", kana: "クライミング" },
  { en: "climber", kana: "クライマー" },
  { en: "lamb", kana: "ラム" },
  { en: "bomb", kana: "ボム" },
  { en: "thumb", kana: "サム" },
  { en: "tomb", kana: "トゥーム" },
  { en: "dumb", kana: "ダム" },
  { en: "plumber", kana: "プラマー" },
  { en: "subtle", kana: "サトル" },
  { en: "island", kana: "アイランド" },
  { en: "aisle", kana: "アイル" },
  { en: "castle", kana: "キャッスル" },
  { en: "listen", kana: "リスン" },
  { en: "listening", kana: "リスニング" },
  { en: "whistle", kana: "ウィッスル" },
  { en: "fasten", kana: "ファスン" },
  { en: "sword", kana: "ソード" },
  { en: "muscle", kana: "マッスル" },
  { en: "science", kana: "サイエンス" },
  { en: "receipt", kana: "レシート" },
  { en: "guess", kana: "ゲス" },
  { en: "foreign", kana: "フォーリン" },
  { en: "who", kana: "フー" },
  { en: "whole", kana: "ホール" },
  /*
   * 用户问「know 的读音是否正确」时顺手把 -ow 这一族核对了一遍。
   * `know` ノウ 本身是对的（词典给的就对），但下面这几个是错的：
   *   knowing  ノーイング  ✗（要和 know 一致：ノウイング）
   *   know-how ノワアウ    ✗（词典里没有，规则层把 w 当辅音读了：ノウハウ）
   *   throwing スロウィン  ✗（throw 词典里是 スロー）：スローイング
   *   flowing  フロウィン  ✗（flow 词典里是 フロウ）：フロウイング
   *   blowing  ブロウィン  ✗（blow 词典里是 ブロウ）：ブロウイング
   *   unforgettable ウンフォーゲタタブブル ✗（规则层的 un- 处理很差）：アンフォーゲタブル
   * 顺带说明：/oʊ/ 在日语外来语里 **ウ 和 ー 两种都通行**（know ノウ、show ショー、
   * snow スノウ、slow スロー），所以判据是"**和同族的词保持一致**"，不是谁更"正确"。
   */
  { en: "knowing", kana: "ノウイング" },
  { en: "knowhow", kana: "ノウハウ" },
  { en: "throwing", kana: "スローイング" },
  { en: "flowing", kana: "フロウイング" },
  { en: "blowing", kana: "ブロウイング" },
  { en: "unforgettable", kana: "アンフォーゲタブル" },
  /*
   * 用户五张截图（英文歌词行）里被**罗马音层抢读**的词。
   *
   * 病根：这些词既不在离线词典、也不在英文词表（core/enwords.js）里，于是
   * 罗马音层按日语音节切开（da-ze / ri-me / sho-ne / bo-on / ho-o），
   * 还标成"确定"（蓝色）—— 层序里罗马音排在在线层前面，大模型也就没机会纠。
   * 规则层对这几个也一样错（词尾哑音 e 和 `oo` 是它已知的两个洞：
   * daze ダゼ、rime リメ、boon ボオン、hoo ホオ）。
   *
   * 所以只能人工钉：读法唯一，而且都是英文通行写法。
   *   -aze 一族：daze デイズ / gaze ゲイズ / maze メイズ / haze ヘイズ /
   *               craze クレイズ / graze グレイズ / raze レイズ / faze フェイズ
   *   -ime 一族：rime ライム（= rhyme）/ lime ライム / dime ダイム / chime チャイム / slime スライム
   *   -oo 一族：boon ブーン / hoo フー / boo ブー / loom ルーム / doom ドゥーム /
   *              broom ブルーム / spoon スプーン / fool フール / hoof フーフ
   *   -one / thaw / anew / woven：shone ショーン / thaw ソー / anew アニュー / woven ウォーヴン
   */
  { en: "daze", kana: "デイズ" },
  { en: "gaze", kana: "ゲイズ" },
  { en: "maze", kana: "メイズ" },
  { en: "haze", kana: "ヘイズ" },
  { en: "craze", kana: "クレイズ" },
  { en: "graze", kana: "グレイズ" },
  { en: "raze", kana: "レイズ" },
  { en: "faze", kana: "フェイズ" },
  { en: "rime", kana: "ライム" },
  { en: "lime", kana: "ライム" },
  { en: "dime", kana: "ダイム" },
  { en: "chime", kana: "チャイム" },
  { en: "slime", kana: "スライム" },
  { en: "boon", kana: "ブーン" },
  { en: "hoo", kana: "フー" },
  { en: "boo", kana: "ブー" },
  { en: "loom", kana: "ルーム" },
  { en: "doom", kana: "ドゥーム" },
  { en: "broom", kana: "ブルーム" },
  { en: "spoon", kana: "スプーン" },
  { en: "fool", kana: "フール" },
  { en: "hoof", kana: "フーフ" },
  { en: "shone", kana: "ショーン" },
  { en: "thaw", kana: "ソー" },
  { en: "anew", kana: "アニュー" },
  { en: "woven", kana: "ウォーヴン" },
  // bye：用户截图 `Say Good Bye` 里规则层读成 バイェ（该 バイ）
  { en: "bye", kana: "バイ" },
  /*
   * 用户截图 `ゆらゆら (AH!!)`：`AH` 被逐字母读成 **エーエイチ** ——
   * `spellOutAcronym` 的"有元音的 2~3 字母缩写"那道闸门只挡**词典里有的词**，
   * 而 `ah` 不在词典里，于是被当成缩写了。`oh` / `uh` 在词典里，所以 `OH` / `UH` 没事。
   * 这一批把常见的**感叹词**补齐（规则层给的 アハー / フー 这种都不对）。
   */
  { en: "ah", kana: "アー" },
  { en: "ahh", kana: "アー" },
  { en: "huh", kana: "ハァ" },
  // tofu：用户截图 `my tofu mentality` 被罗马音层读成 トフ（该 トウフ）；ramen 同理（ラメン ✗）
  { en: "tofu", kana: "トウフ" },
  { en: "ramen", kana: "ラーメン" },
  // mentality：同一张截图里规则层读成 メンタリタイー ✗（该 メンタリティー）
  { en: "mentality", kana: "メンタリティー" },
  /*
   * 用户问「notes 的读音」时核出来的：**复数/变形形的读音**是大模型词表最容易错的地方。
   *   notes  ノート  ✗（那是单数；复数该 ノーツ，同族的 dates デイツ / rates レーツ 都对）
   *   noting ノティン ✗（该 ノーティング）
   *   bites  ビテス ✗（词尾哑 e + s：该 バイツ）—— kites キテス / mates マテス /
   *          bones ボネス / zones ゾネス 都是同一个病：把哑 e 当元音读了
   *   footnote フォオタノテ ✗（该 フットノート）／keynote ケイノテ ✗（该 キーノート）
   * 规则层那边也有同一个洞（词尾哑 e 后面再跟 s / ing 时不再判长音），
   * 但常见变形词基本都在词表里，人工钉这一批就够用；模型纠正过的词还会被
   * 自动沉淀成离线词条（见 core/learn.js），所以这类词会越用越准。
   * （`notes` 的老条目在上面那份字母序表里，这里就直接改掉、不再补一条 ——
   *   同一个词两种写法构建器会中止，见 tools/build-dict.js。）
   */
  { en: "noting", kana: "ノーティング" },
  { en: "bites", kana: "バイツ" },
  { en: "kites", kana: "カイツ" },
  { en: "mates", kana: "メイツ" },
  { en: "bones", kana: "ボーンズ" },
  { en: "zones", kana: "ゾーンズ" },
  { en: "footnote", kana: "フットノート" },
  { en: "footnotes", kana: "フットノーツ" },
  { en: "keynote", kana: "キーノート" },
  /*
   * 音乐术语（意大利语速度/力度/曲式词）。
   *
   * 用户发的截图：`(Lento, presto, andante larghetto)` 标的是 レント / プレスト /
   * アンダンテ / ラルゲット —— 四个读音都对，但**离线时有两个是错的**
   * （presto 规则读成 プレサト、larghetto 读成 ラーーエタト），
   * 截图里之所以对，是大模型临时给的（等于每听一遍都要花一次请求）。
   * 查下来整个音乐术语区在词典里是空的（只有 tempo / opera / symphony 这种通用词），
   * 而这一区的读法**唯一**（日语音乐术语有固定写法），正是该人工钉死的类型。
   *
   * 例外：`grave` **不收** —— 意大利语术语读 グラーヴェ，英语"墓"读 グレイヴ，
   * 两可，交给大模型按整句语境判（和 do/re/mi 那些一个道理）。
   */
  { en: "lento", kana: "レント" },
  { en: "presto", kana: "プレスト" },
  { en: "prestissimo", kana: "プレスティッシモ" },
  { en: "andante", kana: "アンダンテ" },
  { en: "andantino", kana: "アンダンティーノ" },
  { en: "larghetto", kana: "ラルゲット" },
  { en: "adagio", kana: "アダージョ" },
  { en: "allegro", kana: "アレグロ" },
  { en: "allegretto", kana: "アレグレット" },
  { en: "moderato", kana: "モデラート" },
  { en: "vivace", kana: "ヴィヴァーチェ" },
  { en: "largo", kana: "ラルゴ" },
  { en: "ritardando", kana: "リタルダンド" },
  { en: "accelerando", kana: "アッチェレランド" },
  { en: "crescendo", kana: "クレッシェンド" },
  { en: "decrescendo", kana: "デクレッシェンド" },
  { en: "diminuendo", kana: "ディミヌエンド" },
  { en: "forte", kana: "フォルテ" },
  { en: "fortissimo", kana: "フォルティッシモ" },
  { en: "pianissimo", kana: "ピアニッシモ" },
  { en: "mezzo", kana: "メッゾ" },
  { en: "mezzoforte", kana: "メッゾフォルテ" },
  { en: "mezzopiano", kana: "メッゾピアノ" },
  { en: "legato", kana: "レガート" },
  { en: "staccato", kana: "スタッカート" },
  { en: "sforzando", kana: "スフォルツァンド" },
  { en: "fermata", kana: "フェルマータ" },
  { en: "dolce", kana: "ドルチェ" },
  { en: "cantabile", kana: "カンタービレ" },
  { en: "maestoso", kana: "マエストーソ" },
  { en: "giocoso", kana: "ジョコーソ" },
  { en: "tranquillo", kana: "トランクィッロ" },
  { en: "animato", kana: "アニマート" },
  { en: "rubato", kana: "ルバート" },
  { en: "ostinato", kana: "オスティナート" },
  { en: "cadenza", kana: "カデンツァ" },
  { en: "tenuto", kana: "テヌート" },
  { en: "marcato", kana: "マルカート" },
  { en: "pizzicato", kana: "ピッツィカート" },
  { en: "glissando", kana: "グリッサンド" },
  { en: "vibrato", kana: "ビブラート" },
  { en: "portamento", kana: "ポルタメント" },
  { en: "tremolo", kana: "トレモロ" },
  { en: "trill", kana: "トリル" },
  { en: "minuet", kana: "メヌエット" },
  { en: "scherzo", kana: "スケルツォ" },
  { en: "rondo", kana: "ロンド" },
  { en: "toccata", kana: "トッカータ" },
  { en: "fugue", kana: "フーガ" },
  { en: "etude", kana: "エチュード" },
  { en: "nocturne", kana: "ノクターン" },
  { en: "waltz", kana: "ワルツ" },
  { en: "tango", kana: "タンゴ" },
  { en: "rhapsody", kana: "ラプソディー" },
  { en: "ballade", kana: "バラード" },
  { en: "sonata", kana: "ソナタ" },
  { en: "concerto", kana: "コンチェルト" },
  { en: "quartet", kana: "カルテット" },
  { en: "quintet", kana: "クインテット" },
  { en: "trio", kana: "トリオ" },
  { en: "ensemble", kana: "アンサンブル" },
  { en: "overture", kana: "オーバーチュア" },
  { en: "prelude", kana: "プレリュード" },
  { en: "aria", kana: "アリア" },
  { en: "soprano", kana: "ソプラノ" },
  { en: "tenor", kana: "テノール" },
  { en: "octave", kana: "オクターヴ" },
  { en: "chord", kana: "コード" },
  { en: "coda", kana: "コーダ" },
  { en: "segno", kana: "セーニョ" },
  { en: "tutti", kana: "トゥッティ" },
  { en: "arco", kana: "アルコ" },
  { en: "cello", kana: "チェロ" },
  { en: "flute", kana: "フルート" },
  { en: "trumpet", kana: "トランペット" },
  /*
   * 用户第二张截图：`Every night brings a dream but the day, relentlessly, keeps me awake`
   * —— 读音都对，但 `relentlessly` / `awake` 当时是**大模型临时给的**，
   * 离线时分别是 レレントレスライー ✗ / アワケ ✗（罗马音层抢的）。
   *
   * 顺带把 -ize 那一族（上一张截图的 `memorize`）也收尾：
   * 规则层现在认得「辅音 + イズ」（见 reading.js 的 EN_IZE），
   * 剩下的"词干本身读不准"的（idolize イドライズ✗、mesmerize メサメライズ✗、
   * socialize ソスイアライズ✗、sympathize サインパトハイズ✗、energize エナージャイズ✗）
   * 人工钉住。`-ise` 拼法两可（promise プロミス vs surprise サプライズ），
   * 所以那一支也走人工词表。
   */
  { en: "every", kana: "エブリ" },
  { en: "everybody", kana: "エブリバディ" },
  { en: "relentless", kana: "リレントレス" },
  { en: "relentlessly", kana: "リレントレスリー" },
  { en: "awake", kana: "アウェイク" },
  { en: "awaken", kana: "アウェイクン" },
  { en: "asleep", kana: "アスリープ" },
  { en: "memorize", kana: "メモライズ" },
  { en: "memorized", kana: "メモライズド" },
  { en: "memorizing", kana: "メモライジング" },
  { en: "memorable", kana: "メモラブル" },
  { en: "realize", kana: "リアライズ" },
  { en: "realizing", kana: "リアライジング" },
  { en: "realise", kana: "リアライズ" },
  { en: "realised", kana: "リアライズド" },
  { en: "realising", kana: "リアライジング" },
  { en: "idolize", kana: "アイドライズ" },
  { en: "mesmerize", kana: "メズマライズ" },
  { en: "socialize", kana: "ソーシャライズ" },
  { en: "sympathize", kana: "シンパサイズ" },
  { en: "energize", kana: "エナジャイズ" },
  { en: "advise", kana: "アドバイズ" },
  { en: "precise", kana: "プリサイス" },
  { en: "surprising", kana: "サプライジング" },
  /*
   * 用户截图：`KiLLKiSS judy... / jude... / juda...`（Ave Mujica 的歌）。
   * 三个里 `juda` ジュダ 是对的，`jude` 被罗马音层切成 ju-de 读成 ジュデ ✗
   * （规则层已经补了词尾 -ude 那条通例，见 reading.js 的 EN_UDE），
   * `judy` ジュダイー ✗ 与 `KiLLKiSS` キララキス ✗ 规则层猜不出来，人工钉死。
   * 顺带把 -ude 那一族的常用词也钉住（规则层现在读得对，钉住只是防回归）。
   */
  { en: "judy", kana: "ジュディ" },
  { en: "jude", kana: "ジュード" },
  { en: "juda", kana: "ジュダ" },
  { en: "killkiss", kana: "キルキス" },
  { en: "rude", kana: "ルード" },
  { en: "gratitude", kana: "グラティテュード" },
  { en: "solitude", kana: "ソリテュード" },
  { en: "magnitude", kana: "マグニテュード" },
  { en: "interlude", kana: "インタールード" },
  /*
   * 用户截图：`憧れた DIVA なん だ` 的 DIVA 被逐字母念成 ディーアイブイエー。
   * 4 个字母以上、带元音的全大写基本都是**词或名字**（DIVA / QUIX / KISS），
   * 所以缩写那条判据已经收窄到 2~3 个字母；这个词本身也钉进词表。
   */
  { en: "diva", kana: "ディーヴァ" },
  /*
   * 法语常用词（用户要"添加对法语的支持"，给了一整首法语歌词当例子）。
   *
   * 规则层（core/langs.js 的 frenchToKatakana）已经能拼出大意，但那套是**近似**：
   * 联诵、哑音 e、开闭音节都判不准（je 会拼成 ジェ、et 会拼成 ウ）。
   * 所以最高频的那批人工钉住，规则层只管剩下的内容词，模型再兜底。
   *
   * **故意不收**英法同形异音的词：son（英语 サン / 法语 ソン）、plus（プラス/プリュ）、
   * grand（グランド/グラン）、cent、pain、main、coin、fin、long、or、fort、tour…
   * 那些只走"法语行才启用"的规则层，英文行不会被带歪。
   */
  { en: "et", kana: "エ" },
  { en: "est", kana: "エ" },
  { en: "es", kana: "エ" },
  { en: "suis", kana: "スィ" },
  { en: "si", kana: "スィ" },
  { en: "je", kana: "ジュ" },
  { en: "le", kana: "ル" },
  { en: "de", kana: "ドゥ" },
  { en: "que", kana: "ク" },
  { en: "qui", kana: "キ" },
  { en: "elle", kana: "エル" },
  { en: "elles", kana: "エル" },
  { en: "il", kana: "イル" },
  { en: "ils", kana: "イル" },
  { en: "nous", kana: "ヌ" },
  { en: "vous", kana: "ヴー" },
  { en: "moi", kana: "モワ" },
  { en: "toi", kana: "トワ" },
  { en: "lui", kana: "リュイ" },
  { en: "on", kana: "オン" },
  { en: "les", kana: "レ" },
  { en: "des", kana: "デ" },
  { en: "mes", kana: "メ" },
  { en: "tes", kana: "テ" },
  { en: "ses", kana: "セ" },
  { en: "ces", kana: "セ" },
  { en: "ce", kana: "ス" },
  { en: "se", kana: "ス" },
  { en: "ne", kana: "ヌ" },
  { en: "dans", kana: "ダン" },
  { en: "mon", kana: "モン" },
  { en: "ton", kana: "トン" },
  { en: "notre", kana: "ノートル" },
  { en: "votre", kana: "ヴォートル" },
  { en: "leur", kana: "ルール" },
  { en: "la", kana: "ラ" },
  { en: "une", kana: "ユヌ" },
  { en: "un", kana: "アン" },
  { en: "cest", kana: "セ" },
  { en: "nest", kana: "ネ" },
  { en: "quil", kana: "キル" },
  { en: "jai", kana: "ジェ" },
  { en: "dun", kana: "ダン" },
  { en: "adieu", kana: "アデュ" },
  { en: "amour", kana: "アムール" },
  { en: "toujours", kana: "トゥジュール" },
  { en: "jamais", kana: "ジャメ" },
  { en: "vie", kana: "ヴィ" },
  { en: "vies", kana: "ヴィ" },
  { en: "monde", kana: "モンド" },
  { en: "coeur", kana: "クール" },
  { en: "ciel", kana: "シエル" },
  { en: "nuit", kana: "ニュイ" },
  { en: "jour", kana: "ジュール" },
  { en: "yeux", kana: "イユ" },
  { en: "beaute", kana: "ボーテ" },
  { en: "doux", kana: "ドゥ" },
  { en: "douce", kana: "ドゥース" },
  { en: "seul", kana: "スル" },
  { en: "seule", kana: "スル" },
  { en: "histoire", kana: "イストワール" },
  { en: "fleur", kana: "フルール" },
  { en: "fleurs", kana: "フルール" },
  { en: "aimer", kana: "エメ" },
  { en: "chanter", kana: "シャンテ" },
  { en: "danser", kana: "ダンセ" },
  { en: "vivre", kana: "ヴィーヴル" },
  { en: "mourir", kana: "ムリール" },
  { en: "voir", kana: "ヴォワール" },
  { en: "savoir", kana: "サヴォワール" },
  { en: "pouvoir", kana: "プヴォワール" },
  { en: "vouloir", kana: "ヴロワール" },
  { en: "etre", kana: "エートル" },
  { en: "avoir", kana: "アヴォワール" },
  { en: "faire", kana: "フェール" },
  { en: "dire", kana: "ディール" },
  { en: "serai", kana: "スレ" },
  { en: "sera", kana: "スラ" },
  { en: "serait", kana: "スレ" },
  { en: "suffit", kana: "スフィ" },
  { en: "pardonner", kana: "パルドネ" },
  { en: "mere", kana: "メール" },
  { en: "pere", kana: "ペール" },
  { en: "frere", kana: "フレール" },
  { en: "soeur", kana: "スール" },
  { en: "lumiere", kana: "リュミエール" },
  { en: "etoile", kana: "エトワール" },
  { en: "etoiles", kana: "エトワール" },
  { en: "reve", kana: "レーヴ" },
  { en: "reves", kana: "レーヴ" },
  { en: "larme", kana: "ラルム" },
  { en: "larmes", kana: "ラルム" },
  { en: "souvenir", kana: "スヴニール" },
  { en: "demain", kana: "ドゥマン" },
  { en: "aujourdhui", kana: "オジュルドュイ" },
  { en: "matin", kana: "マタン" },
  { en: "soir", kana: "ソワール" },
  { en: "printemps", kana: "プランタン" },
  { en: "hiver", kana: "イヴェール" },
  { en: "automne", kana: "オトンヌ" },
  { en: "chanson", kana: "シャンソン" },
  { en: "musique", kana: "ミュジック" },
  { en: "danse", kana: "ダンス" },
  { en: "ange", kana: "アンジュ" },
  { en: "terre", kana: "テール" },
  { en: "mer", kana: "メール" },
  { en: "feu", kana: "フ" },
  { en: "vent", kana: "ヴァン" },
  { en: "pluie", kana: "プリュイ" },
  { en: "soleil", kana: "ソレイユ" },
  { en: "lune", kana: "リュヌ" },
  { en: "chemin", kana: "シュマン" },
  { en: "maison", kana: "メゾン" },
  { en: "ville", kana: "ヴィル" },
  { en: "pays", kana: "ペイ" },
  { en: "homme", kana: "オム" },
  { en: "femme", kana: "ファム" },
  { en: "enfant", kana: "アンファン" },
  { en: "ami", kana: "アミ" },
  { en: "amie", kana: "アミ" },
  { en: "ca", kana: "サ" },
  { en: "nourrit", kana: "ヌリ" },
  { en: "seraitil", kana: "スレティル" },
  { en: "fleurira", kana: "フルリラ" },
  { en: "pouvais", kana: "プヴェ" },
  { en: "encore", kana: "アンコール" },
  { en: "ensemble", kana: "アンサンブル" },
  { en: "regard", kana: "ルガール" },
  { en: "voix", kana: "ヴォワ" },
  { en: "quel", kana: "ケル" },
  { en: "quelle", kana: "ケル" },
  { en: "quelque", kana: "ケルク" },
  { en: "merci", kana: "メルシー" },
  { en: "bonjour", kana: "ボンジュール" },
  { en: "chateau", kana: "シャトー" },
  { en: "rose", kana: "ローズ" },
  { en: "note", kana: "ノート" },
  /*
   * 英文拼写规则的两个已知死角（用户用例里正好都碰上了）：
   *
   *   1. `str-` 开头的连缀：规则层把 s 当独立音节，stronger 读成 サトロンゲー、
   *      stranger 读成 サトランゲー（strong / strange 本身在词典里，所以只漏了变形）；
   *   2. 「元音 + 单辅音 + 词尾 e」的 a（cage キャジ 应该是 ケイジ）——
   *      cake / game / page / place 这些都在词典里，cage 恰好漏了。
   *
   * 两个都是"没歧义、歌词里常见"的那一类，按项目惯例人工钉死；
   * 顺带把同族的变形也补齐（不然下一首歌又会在 -er / -est / 复数上踩同一脚）。
   */
  { en: "stronger", kana: "ストロンガー" },
  { en: "strongest", kana: "ストロンゲスト" },
  { en: "stranger", kana: "ストレンジャー" },
  { en: "strangers", kana: "ストレンジャーズ" },
  { en: "cage", kana: "ケイジ" },
  { en: "cages", kana: "ケイジズ" },
  { en: "caged", kana: "ケイジド" },
  /*
   * 德语 `mit`（用户截图 `Sieh mit deinen Augen`）：词典里原本是 **MIT**（学院缩写）
   * 的字母名 エムアイティー，小写的 mit 也被它带歪了。
   * mit 是德语最常用的介词之一、读法唯一（ミット）→ 人工钉死。
   * 缩写那条（逐字母念）排在词典**后面**，所以全大写的 `MIT` 也吃这条 ——
   * 但歌词里出现德语 `mit` 的概率远高于学院缩写，按这一侧收。
   */
  { en: "mit", kana: "ミット" },
  /*
   * 日语来源的英文词（用户给的 https://www.sljfaq.org/afaq/japanese-in-english.html）。
   *
   * 这一类词在日语歌词里写成拉丁字母时，读的是**日语原词**，不是英文音译：
   * `kudzu` 是 クズ（葛）、`honcho` 是 ハンチョウ（班長）、`rickshaw` 是 ジンリキシャ（人力車）。
   * 我们自己的英文规则读不对（クダズ / ホンチョ / リックシオー），罗马音层也接不住
   * （这些拼法不是日语罗马字），所以按项目惯例人工钉死。
   *
   * 只收**英语里没有别的常用义**的那一批；剩下 30 多个实测本来就对
   * （sushi スシ、tempura テンプラ、manga マンガ…），靠罗马音层就够。故意不收的：
   *   go（英语"去"）、sake（英语"缘故"）、soy（英语"大豆"）—— 收进去会把常见英文词读歪。
   * ginkgo / noh / tycoon 按日语原词读（イチョウ / ノウ / タイクン）—— 日语歌词里就是这个意思。
   */
  { en: "adzuki", kana: "アズキ" },
  { en: "bokeh", kana: "ボケ" },
  { en: "ginkgo", kana: "イチョウ" },
  { en: "honcho", kana: "ハンチョウ" },
  { en: "kombucha", kana: "コンブチャ" },
  { en: "kudzu", kana: "クズ" },
  { en: "moxa", kana: "モグサ" },
  { en: "noh", kana: "ノウ" },
  { en: "rickshaw", kana: "ジンリキシャ" },
  { en: "shoji", kana: "ショウジ" },
  { en: "sudoku", kana: "スードク" },
  { en: "tycoon", kana: "タイクン" },
  { en: "zori", kana: "ゾウリ" },
];
